# Generated by Django 3.2.4 on 2022-10-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20221018_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
