# Generated by Django 3.2.4 on 2022-10-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_vehiculos_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='ubicacion',
        ),
    ]
